### ISSUE TITLE
`memo` works incorrectly

### ISSUE THREAD

**Issue by funny-falcon** [true-grue/peco#10]
`memo` remembers whole resulting peco state, including `s.stack`, and returns it.

But, it doesn't use incoming `s.stack` as a key part. This may lead to returning of wrong stack on match.

I found it when tried to play with `npeek`:
```diff
diff --git a/test_logo.py b/test_logo.py
index 831edac..e412b8e 100644
--- a/test_logo.py
+++ b/test_logo.py
@@ -26,16 +26,16 @@ name = seq(tok(r'[a-zA-Z_][a-zA-Z0-9_]*'), when(lambda x: x not in KW))
 num = seq(tok(r'-?[0-9]+'), to(lambda x: float(x)))
 
 cmd = lambda s: cmd(s)
-block = seq(group(many(cmd)), mkblock)
+block = lambda end: seq(group(many(seq(npeek(end), cmd))), end, mkblock)
 
 cmd = alt(
     seq(tok('fd|bk|lt|rt'), num, mkmove),
     seq(tok('pu|pd'), mkpen),
-    seq(skip('repeat'), num, skip(r'\['), block, skip(r'\]'), mkrepeat),
+    seq(skip('repeat'), num, skip(r'\['), block( skip(r'\]')), mkrepeat),
     seq(name, mkcall)
 )
 
-func = seq(skip('to'), name, block, skip('end'), mkfunc)
+func = seq(skip('to'), name, block( skip('end')), mkfunc)
 main = seq(group(many(alt(cmd, func))), ws, mkblock)
```
Such modification shall not fail test, but fails since `npeek` leads to memoization of wrong `s.stack`.

Certainly, there are ways to trigger bug without `npeek`. 

Simplest way to fix is:
```diff
@@ -98,7 +101,7 @@ def npeek(f):
 
 def memo(f):
     def parse(s):
-        key = f, s.pos
+        key = f, s.pos, s.stack
         tab = s.glob['tab']
         if key not in tab:
             tab[key] = f(s)
@@ -108,13 +111,12 @@ def memo(f):
 
 def left(f):
     def parse(s):
-        key = f, s.pos
+        key = f, s.pos, s.stack
         tab = s.glob['tab']
         if key not in tab:
             tab[key] = s._replace(ok=False)
-            pos = s.pos
-            while (s := f(s._replace(pos=pos))).pos > tab[key].pos:
-                tab[key] = s
+            while (ns := f(s)).pos > tab[key].pos:
+                tab[key] = ns
         return tab[key]
     return parse
```
Unfortunately it doesn't work when mutable values are pushed on the `s.stack`.

`str(s.stack)` will work, but will consume a lot of memory and time. `hash(str(s.stack))` will consume less memory, but still a lot of time.

There ways to incrementally hash value of `s.stack`, storing current hash in third field.

**Comment by funny-falcon** [comment]
Other approach: put to memo only if stack only grew or didn't change at all, and remember only this growing, not whole stack. Then on retrieving from memo append this growing part.

Still it is quite fragile. Especially if some additional state will be introduced as suggested in #6 .

**Comment by funny-falcon** [comment]
Looks like I found solution in #11

**Comment by funny-falcon** [comment]
Solution is use `id(s.stack)` as part of key **and** keep reference to `s.stack` therefore its `id` could not be reused.

Certainly, it will somewhat increase memory usage. And perhaps sequential numbering is still better.

**Comment by true-grue** [comment]
Thanks! Yes, the solution of keeping the s.stack reference seems to be the easiest. I added my implementation, please comment :)

**Comment by funny-falcon** [comment]
Your commit looks good to me.

I removed my version from #11 , leaving only `cut` operator there.
