### ISSUE TITLE
eof in parse blocks iterative parsing

### ISSUE THREAD

**Issue by funny-falcon** [true-grue/peco#8]
https://github.com/true-grue/peco/blob/1d9a703e6a6bde899950acfa9e5c9726f0227f32/peco.py#L129-L130

Without this eof it is possible to continue parsing using returned state with stack cleared.

For example, this way could be parsed “lines with json objects” file one object at a time, or CSV one line at a time, or strict dialect of C/Pascal/Go/IDL/proto without nested declarations.

Probably it is better to remove `parse` function and expose `init` function that creates `Peco` state for string, and `cont`/`forward` (I’m weak at naming) which resets stack?

**Comment by true-grue** [comment]
So here's a simpler parse implementation. Now it's not hard to write your own version. What do you think?

**Comment by funny-falcon** [comment]
I believe, there should be helper to reset `ok`, `stack`, `glob['err']` and `glob['tab']`.

But I will delay this discussion for a bit.
